In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

INPUT_PATH = Path("../data/processed/schools_with_exposure.csv")
OUT_DIR = Path("../data/processed")
OUT_DIR.mkdir(parents=True, exist_ok=True)

In [2]:
df = pd.read_csv(INPUT_PATH)

print("Shape:", df.shape)
print("Columns:")
print(df.columns.tolist())
df.head()

Shape: (2423, 61)
Columns:
['District', 'School Name', 'Address', 'SchoolLevel', 'Latitude', 'Longitude', 'Type', 'nearest_station_id', 'nearest_station_name', 'distance_km', 'station_id', 'station_name', 'network', 'n_days', 'date_min', 'date_max', 'PM2.5 (µg/m³)_mean', 'PM2.5 (µg/m³)_median', 'PM2.5 (µg/m³)_max', 'PM2.5 (µg/m³)_missing_pct', 'PM10 (µg/m³)_mean', 'PM10 (µg/m³)_median', 'PM10 (µg/m³)_max', 'PM10 (µg/m³)_missing_pct', 'NO (µg/m³)_mean', 'NO (µg/m³)_median', 'NO (µg/m³)_max', 'NO (µg/m³)_missing_pct', 'NO2 (µg/m³)_mean', 'NO2 (µg/m³)_median', 'NO2 (µg/m³)_max', 'NO2 (µg/m³)_missing_pct', 'NOx (ppb)_mean', 'NOx (ppb)_median', 'NOx (ppb)_max', 'NOx (ppb)_missing_pct', 'NH3 (µg/m³)_mean', 'NH3 (µg/m³)_median', 'NH3 (µg/m³)_max', 'NH3 (µg/m³)_missing_pct', 'SO2 (µg/m³)_mean', 'SO2 (µg/m³)_median', 'SO2 (µg/m³)_max', 'SO2 (µg/m³)_missing_pct', 'CO (mg/m³)_mean', 'CO (mg/m³)_median', 'CO (mg/m³)_max', 'CO (mg/m³)_missing_pct', 'Ozone (µg/m³)_mean', 'Ozone (µg/m³)_median', 'Ozone (µg/m³)_max', 'Ozone (µg/m³)_missing_pct', 'Benzene (µg/m³)_mean', 'Benzene (µg/m³)_median', 'Benzene (µg/m³)_max', 'Benzene (µg/m³)_missing_pct', 'Toluene (µg/m³)_mean', 'Toluene (µg/m³)_median', 'Toluene (µg/m³)_max', 'Toluene (µg/m³)_missing_pct', 'exposure_confidence']

,District,School Name,Address,SchoolLevel,Latitude,Longitude,Type,nearest_station_id,nearest_station_name,distance_km,...,Ozone (µg/m³)_missing_pct,Benzene (µg/m³)_mean,Benzene (µg/m³)_median,Benzene (µg/m³)_max,Benzene (µg/m³)_missing_pct,Toluene (µg/m³)_mean,Toluene (µg/m³)_median,Toluene (µg/m³)_max,Toluene (µg/m³)_missing_pct,exposure_confidence
0,North West A,The Vivekanand School,"Shiv Mandir Colony, Narela, Delhi-40",Sr.Secondary,28.870837,77.080305,Unaided,STN_029,Narela,5.740,...,0.821918,2.711808,1.99,13.45,0.0,142.138164,125.77,407.23,0.0,Medium
1,North West A,NATIONAL PUBLIC SCHOOL,"SAFIABAD ROAD NARELA, DELHI - 110040",Secondary,28.863631,77.085591,Unaided,STN_029,Narela,4.809,...,0.821918,2.711808,1.99,13.45,0.0,142.138164,125.77,407.23,0.0,High
2,North West A,Singhu-G(Co-Ed)SSS,"Singhu,Delhi",Sr.Secondary,28.861792,77.136931,Govt,STN_001,Alipur,5.399,...,0.547945,1.352959,0.58,52.05,0.0,4.921589,1.71,62.62,0.0,Medium
3,North West A,"Narela,Sect. A-6, Pkt-2 -SBV","GBSSS, Sect. A-6, Pkt-2, Narela, Delhi-110040",Sarvodaya Sr.Secondary,28.856882,77.100818,Govt,STN_029,Narela,3.787,...,0.821918,2.711808,1.99,13.45,0.0,142.138164,125.77,407.23,0.0,High
4,North West A,DAV CENTENARY PUBLIC SCHOOL,NARELA DELHI - 110040,Sr.Secondary,28.856308,77.084533,Unaided,STN_029,Narela,4.092,...,0.821918,2.711808,1.99,13.45,0.0,142.138164,125.77,407.23,0.0,High

In [3]:
analysis_cols = [
    "District",
    "School Name",
    "Address",
    "SchoolLevel",
    "Latitude",
    "Longitude",
    "Type",
    "nearest_station_id",
    "nearest_station_name",
    "distance_km",
    "exposure_confidence",
    "PM2.5 (µg/m³)_mean",
    "PM10 (µg/m³)_mean",
    "NO2 (µg/m³)_mean",
    "station_name",
    "network"
]

analysis_df = df[analysis_cols].copy()

print("Analysis table shape:", analysis_df.shape)
analysis_df.head()

Analysis table shape: (2423, 16)

,District,School Name,Address,SchoolLevel,Latitude,Longitude,Type,nearest_station_id,nearest_station_name,distance_km,exposure_confidence,PM2.5 (µg/m³)_mean,PM10 (µg/m³)_mean,NO2 (µg/m³)_mean,station_name,network
0,North West A,The Vivekanand School,"Shiv Mandir Colony, Narela, Delhi-40",Sr.Secondary,28.870837,77.080305,Unaided,STN_029,Narela,5.740,Medium,109.104000,205.852384,23.884438,Narela,DPCC
1,North West A,NATIONAL PUBLIC SCHOOL,"SAFIABAD ROAD NARELA, DELHI - 110040",Secondary,28.863631,77.085591,Unaided,STN_029,Narela,4.809,High,109.104000,205.852384,23.884438,Narela,DPCC
2,North West A,Singhu-G(Co-Ed)SSS,"Singhu,Delhi",Sr.Secondary,28.861792,77.136931,Govt,STN_001,Alipur,5.399,Medium,99.947233,207.102438,36.297616,Alipur,DPCC
3,North West A,"Narela,Sect. A-6, Pkt-2 -SBV","GBSSS, Sect. A-6, Pkt-2, Narela, Delhi-110040",Sarvodaya Sr.Secondary,28.856882,77.100818,Govt,STN_029,Narela,3.787,High,109.104000,205.852384,23.884438,Narela,DPCC
4,North West A,DAV CENTENARY PUBLIC SCHOOL,NARELA DELHI - 110040,Sr.Secondary,28.856308,77.084533,Unaided,STN_029,Narela,4.092,High,109.104000,205.852384,23.884438,Narela,DPCC

In [4]:
print("Total schools:", len(analysis_df))
print("Unique districts:", analysis_df["District"].nunique())
print("Unique school types:", analysis_df["Type"].nunique())
print("Unique nearest stations:", analysis_df["nearest_station_id"].nunique())

print("\nMissing values:")
print(analysis_df.isna().sum().sort_values(ascending=False).head(15))

Total schools: 2423
Unique districts: 16
Unique school types: 2
Unique nearest stations: 44

Missing values:
PM2.5 (µg/m³)_mean      138
PM10 (µg/m³)_mean       138
NO2 (µg/m³)_mean        138
station_name             57
network                  57
Address                   2
District                  0
School Name               0
SchoolLevel               0
Latitude                  0
Longitude                 0
Type                      0
nearest_station_id        0
nearest_station_name      0
distance_km               0
dtype: int64

##### District Summary Table
This groups all schools by district and calculates average exposure and distance.

In [5]:
district_summary = (
    analysis_df
    .groupby("District", dropna=False)
    .agg(
        school_count=("School Name", "count"),
        avg_pm25=("PM2.5 (µg/m³)_mean", "mean"),
        median_pm25=("PM2.5 (µg/m³)_mean", "median"),
        avg_pm10=("PM10 (µg/m³)_mean", "mean"),
        avg_no2=("NO2 (µg/m³)_mean", "mean"),
        avg_distance_km=("distance_km", "mean"),
        max_distance_km=("distance_km", "max"),
        unique_stations_used=("nearest_station_id", "nunique")
    )
    .reset_index()
)

district_summary["avg_pm25"] = district_summary["avg_pm25"].round(2)
district_summary["median_pm25"] = district_summary["median_pm25"].round(2)
district_summary["avg_pm10"] = district_summary["avg_pm10"].round(2)
district_summary["avg_no2"] = district_summary["avg_no2"].round(2)
district_summary["avg_distance_km"] = district_summary["avg_distance_km"].round(2)
district_summary["max_distance_km"] = district_summary["max_distance_km"].round(2)

district_summary = district_summary.sort_values(
    by="avg_pm25", ascending=False
).reset_index(drop=True)

print("District summary shape:", district_summary.shape)
district_summary.head(10)

District summary shape: (16, 9)

,District,school_count,avg_pm25,median_pm25,avg_pm10,avg_no2,avg_distance_km,max_distance_km,unique_stations_used
0,North West B-II,146,115.51,116.04,237.36,37.43,3.81,11.34,5
1,North West B-I,180,114.84,114.85,253.21,48.54,2.25,5.98,6
2,North West A,225,111.45,112.19,225.67,38.81,2.44,8.92,12
3,North,98,102.38,97.67,205.04,44.66,2.27,4.18,7
4,East,251,102.11,101.34,217.35,51.16,2.38,7.87,9
5,West A,117,96.86,94.28,198.55,47.70,2.65,5.58,8
6,South West A,90,95.51,88.32,192.92,48.14,2.15,5.07,10
7,South East,177,95.00,92.05,198.71,49.11,2.49,7.14,7
8,South,139,93.50,92.05,186.76,40.98,2.41,7.50,9
9,North East-I,186,93.47,96.23,187.61,35.50,2.59,6.95,3

##### School Type Summary Table
This compares Govt, Unaided, etc.

In [7]:
type_summary = (
    analysis_df
    .groupby("Type", dropna=False)
    .agg(
        school_count=("School Name", "count"),
        avg_pm25=("PM2.5 (µg/m³)_mean", "mean"),
        median_pm25=("PM2.5 (µg/m³)_mean", "median"),
        avg_pm10=("PM10 (µg/m³)_mean", "mean"),
        avg_no2=("NO2 (µg/m³)_mean", "mean"),
        avg_distance_km=("distance_km", "mean"),
        max_distance_km=("distance_km", "max"),
        unique_stations_used=("nearest_station_id", "nunique")
    )
    .reset_index()
)

type_summary["avg_pm25"] = type_summary["avg_pm25"].round(2)
type_summary["median_pm25"] = type_summary["median_pm25"].round(2)
type_summary["avg_pm10"] = type_summary["avg_pm10"].round(2)
type_summary["avg_no2"] = type_summary["avg_no2"].round(2)
type_summary["avg_distance_km"] = type_summary["avg_distance_km"].round(2)
type_summary["max_distance_km"] = type_summary["max_distance_km"].round(2)

type_summary = type_summary.sort_values(
    by="avg_pm25", ascending=False
).reset_index(drop=True)

print("Type summary shape:", type_summary.shape)
type_summary

Type summary shape: (2, 9)

,Type,school_count,avg_pm25,median_pm25,avg_pm10,avg_no2,avg_distance_km,max_distance_km,unique_stations_used
0,Govt,1082,98.37,97.67,205.36,45.70,2.6,10.93,43
1,Unaided,1341,97.77,97.67,205.06,44.73,2.7,15.20,44

##### School Level Summary Table
This compares Primary / Middle / Secondary / Sr.Secondary.

In [8]:
level_summary = (
    analysis_df
    .groupby("SchoolLevel", dropna=False)
    .agg(
        school_count=("School Name", "count"),
        avg_pm25=("PM2.5 (µg/m³)_mean", "mean"),
        median_pm25=("PM2.5 (µg/m³)_mean", "median"),
        avg_pm10=("PM10 (µg/m³)_mean", "mean"),
        avg_distance_km=("distance_km", "mean"),
        max_distance_km=("distance_km", "max")
    )
    .reset_index()
)

level_summary["avg_pm25"] = level_summary["avg_pm25"].round(2)
level_summary["median_pm25"] = level_summary["median_pm25"].round(2)
level_summary["avg_pm10"] = level_summary["avg_pm10"].round(2)
level_summary["avg_distance_km"] = level_summary["avg_distance_km"].round(2)
level_summary["max_distance_km"] = level_summary["max_distance_km"].round(2)

level_summary = level_summary.sort_values(
    by="avg_pm25", ascending=False
).reset_index(drop=True)

print("Level summary shape:", level_summary.shape)
level_summary

Level summary shape: (16, 7)

,SchoolLevel,school_count,avg_pm25,median_pm25,avg_pm10,avg_distance_km,max_distance_km
0,Special School (Secondary),1,116.04,116.04,232.26,2.90,2.90
1,Virtual School,1,109.88,109.88,201.49,0.52,0.52
2,Special School (Sr.Secondary),3,103.14,101.46,199.32,1.71,2.18
3,CM SHRI School (Nur-XII)(Sr.Secondary),37,102.44,108.24,211.03,2.69,7.91
4,Special School (Primary),1,101.34,101.34,219.14,1.35,1.35
5,Sarvodaya Sr.Secondary,453,99.51,101.34,208.79,2.56,10.92
6,SOSE(Sr.Secondary),33,99.50,99.48,207.53,2.27,4.96
7,Sr.Secondary,996,99.35,101.30,207.65,2.64,10.93
8,Special School (Middle),2,98.79,98.79,205.46,1.93,2.51
9,Sarvodaya Secondary,5,98.70,97.67,201.49,1.87,3.84
10,Sarvodaya Middle,7,98.67,97.67,204.41,2.47,7.14
11,CM SHRI School (VI-XII)(Sr.Secondary),38,97.16,97.67,202.46,2.43,7.18
12,Secondary,340,96.08,96.23,202.68,2.82,11.34
13,Middle,503,95.04,96.23,198.51,2.74,15.20
14,Primary,2,90.16,90.16,211.47,1.12,1.73
15,RPVV(Sr.Secondary),1,NaN,NaN,NaN,2.21,2.21

##### Top Exposed Schools Ranking
This gives the schools with the highest PM2.5 exposure proxy.

In [9]:
top_exposed_schools = (
    analysis_df
    .sort_values(
        by=["PM2.5 (µg/m³)_mean", "distance_km"],
        ascending=[False, True]
    )
    .reset_index(drop=True)
)

top_exposed_schools = top_exposed_schools[
    [
        "District",
        "School Name",
        "Address",
        "Type",
        "SchoolLevel",
        "nearest_station_name",
        "distance_km",
        "PM2.5 (µg/m³)_mean",
        "PM10 (µg/m³)_mean",
        "NO2 (µg/m³)_mean",
        "exposure_confidence"
    ]
]

top_exposed_schools.head(20)

,District,School Name,Address,Type,SchoolLevel,nearest_station_name,distance_km,PM2.5 (µg/m³)_mean,PM10 (µg/m³)_mean,NO2 (µg/m³)_mean,exposure_confidence
0,South,ST. ANTHONYS SR. SEC SCHOOL,"C-6, S.D-A, Hauz Khas, Pin-110016",Unaided,Sr.Secondary,IIT Delhi,0.901,159.850323,261.914516,57.109355,High
1,South,MOTHERS INTERNATIONAL SCHOOL,SRI AUROBINDO NEW DELHI - 110016,Unaided,Sr.Secondary,IIT Delhi,0.929,159.850323,261.914516,57.109355,High
2,South,MIRAMBIKA FREE PROGRESS SCHOOL,"SRI AUROBINDO EDUCATION SOCIETY, SRI AUROBINDO...",Unaided,Secondary,IIT Delhi,1.025,159.850323,261.914516,57.109355,High
3,South,ST. PAULS SCHOOL,"C-3, SDA, HAUZ KHAS NEW DELHI",Unaided,Sr.Secondary,IIT Delhi,1.082,159.850323,261.914516,57.109355,High
4,South,SAHODYA SR. SECONDARY SCHOOL,"C-1, Safdarjang Development Area, New Delhi-11...",Unaided,Sr.Secondary,IIT Delhi,1.424,159.850323,261.914516,57.109355,High
5,North West A,PUBLIC MODEL SCHOOL,K - 244 - 246 JAHANGIR PURI DELHI - 110033,Unaided,Middle,Jahangirpuri,0.385,130.802849,262.515753,50.482822,High
6,North West A,"Jahangirpuri, Block K-GGSSS","K-Block, Jahangripuri",Govt,Sr.Secondary,Jahangirpuri,0.438,130.802849,262.515753,50.482822,High
7,North West A,"Jahangirpuri, Block K-GBSSS","Block-K, Jahangirpuri",Govt,Sr.Secondary,Jahangirpuri,0.442,130.802849,262.515753,50.482822,High
8,North West A,"Jahangirpuri, Block D-GBSSS","Jahangirpuri, Delhi-33",Govt,Sr.Secondary,Jahangirpuri,0.533,130.802849,262.515753,50.482822,High
9,North West A,"Sarvodaya Kanya Vidyalaya (Rani Chennama), D -...","D-Block, Jahangirpuri",Govt,Sarvodaya Sr.Secondary,Jahangirpuri,0.592,130.802849,262.515753,50.482822,High
10,North West A,"Jahangirpuri, Block A- SBV","Jahangirpuri, Delhi-33",Govt,Sarvodaya Sr.Secondary,Jahangirpuri,0.680,130.802849,262.515753,50.482822,High
11,North West A,"Jahangirpuri, Block A, No.2 - SKV","Jahangirpui, Block-A",Govt,Sarvodaya Sr.Secondary,Jahangirpuri,0.684,130.802849,262.515753,50.482822,High
12,North West A,"Jahangirpuri, Block E-GBSSS","Block-E, Jahangirpuri",Govt,Sr.Secondary,Jahangirpuri,0.733,130.802849,262.515753,50.482822,High
13,North West A,"Jahangirpuri, Block E-GGSSS-1309258","Jahangirpuri, Delhi-33",Govt,Sr.Secondary,Jahangirpuri,0.740,130.802849,262.515753,50.482822,High
14,North West A,"CM SHRI School, Plot No.5, A-Block, Jahangirpuri,","Sarvodaya Kanya Vidyalaya, Plo No.5, A-Block, ...",Govt,CM SHRI School (Nur-XII)(Sr.Secondary),Jahangirpuri,0.935,130.802849,262.515753,50.482822,High
15,North West A,DAYANAND PUBLIC SCHOOL (ARYA SAMAJ),MODEL TOWN III,Unaided,Secondary,Jahangirpuri,1.081,130.802849,262.515753,50.482822,High
16,North West A,SRI GURU NANAK PUBLIC SCHOOL,"BANGLOW ROAD, ADARSH NAGAR, DELHI-33",Unaided,Sr.Secondary,Jahangirpuri,1.318,130.802849,262.515753,50.482822,High
17,North West A,JYOTI MODEL SR. SEC. SCHOOL,"C-18, ADARSH NAGAR, DELHI-33",Unaided,Sr.Secondary,Jahangirpuri,1.390,130.802849,262.515753,50.482822,High
18,North West A,Kewal Park-G(Co-ed)SSS,Kewal Park Azad Pur Delhi,Govt,Sr.Secondary,Jahangirpuri,1.465,130.802849,262.515753,50.482822,High
19,North West A,Navjeevan Model School,"Mahendra Park,Jahangir Pur",Unaided,Middle,Jahangirpuri,1.490,130.802849,262.515753,50.482822,High

##### Farthest Schools From Monitoring Stations
This helps identify monitoring gaps.

In [10]:
farthest_schools = (
    analysis_df
    .sort_values(by="distance_km", ascending=False)
    .reset_index(drop=True)
)

farthest_schools = farthest_schools[
    [
        "District",
        "School Name",
        "Address",
        "Type",
        "SchoolLevel",
        "nearest_station_name",
        "distance_km",
        "PM2.5 (µg/m³)_mean",
        "exposure_confidence"
    ]
]

farthest_schools.head(20)

,District,School Name,Address,Type,SchoolLevel,nearest_station_name,distance_km,PM2.5 (µg/m³)_mean,exposure_confidence
0,West B,SUNRISE CONVENT SCHOOL,"H.NoD-59/280,StreetNo D-Block,Sector-15,Villag...",Unaided,Middle,Aya Nagar,15.200,76.782384,Low
1,North West B-II,R.K. International School,"V & PO Nizampur, Delhi",Unaided,Secondary,Bawana,11.335,123.343562,Low
2,West B,"Govt. Boys Sr. Sec. School, Tikri Kalan, No. 1...",Tikri Kalan,Govt,Sr.Secondary,NSIT Dwarka,10.928,72.996822,Low
3,West B,"Government Girls Sr. Sec. School, Tikri Kalan",Tikri Kalan,Govt,Sr.Secondary,NSIT Dwarka,10.928,72.996822,Low
4,West B,"Sarvodaya Kanya Vidyalaya, Tikri Kalan-1617012",Tikri Kalan,Govt,Sarvodaya Sr.Secondary,NSIT Dwarka,10.925,72.996822,Low
5,West B,"Government Boys Sr. Sec. School, Tikri Kalan, ...",Tikri Kalan,Govt,Sr.Secondary,NSIT Dwarka,10.925,72.996822,Low
6,North West B-II,Nizam Pur-Sarvodaya (Co-ed) Vidyalaya,Vill & P. O. Nizampur,Govt,Sarvodaya Sr.Secondary,Bawana,10.590,123.343562,Low
7,North West B-II,Vanasthali Public School,"Ghewra, Nizampur Main Road, Delhi 81",Unaided,Sr.Secondary,Bawana,10.514,123.343562,Low
8,West B,NEW BAL VIKAS PUBLIC SCHOOL,TIKRI KALAN,Unaided,Middle,NSIT Dwarka,10.144,72.996822,Low
9,North West B-II,Sawada(Ghevra) Colony H-Block- SV,Sawada(Ghevra) Colony H-Block,Govt,Sarvodaya Sr.Secondary,Mundka,9.940,114.845699,Medium
10,West B,Prince Public School,"Tikri Kalan, New Delhi-110041",Unaided,Secondary,Mundka,9.591,114.845699,Medium
11,North West B-II,Ganga International School,"Swada Nizampur,Delhi",Unaided,Sr.Secondary,Mundka,9.582,114.845699,Medium
12,North West B-II,"Sawada(Ghevra) Colony, B-Block- SBV",Sawada(Ghevra) Colony B-Block,Govt,Sarvodaya Sr.Secondary,Mundka,9.487,114.845699,Medium
13,North West B-II,"Sawada(Ghevra) Colony, A-Block- SKV",Sawada(Ghevra) Colony A-Block,Govt,Sarvodaya Sr.Secondary,Mundka,9.483,114.845699,Medium
14,North West B-II,B.R. Public School,"Village Jaunti, Delhi",Unaided,Middle,Bawana,9.131,123.343562,Medium
15,North West B-II,ARISTOTLE PUBLIC SCHOOL,NEAR BUS STAND QUTOAB GARH DELHI,Unaided,Secondary,Bawana,8.996,123.343562,Medium
16,North West B-II,Jaunti-SV,Jaunti,Govt,Sarvodaya Sr.Secondary,Bawana,8.983,123.343562,Medium
17,North West B-II,Qutabgarh-SKV,Qutabgarh,Govt,Sarvodaya Sr.Secondary,Bawana,8.934,123.343562,Medium
18,North West A,MOTHER KHAZANI SR. SEC. SCHOOL,"MUNGESHPUR, VIA QUTABGARH DELHI",Unaided,Sr.Secondary,Bawana,8.919,123.343562,Medium
19,North West A,Katewara-GBSSS,Katewara,Govt,Sr.Secondary,Bawana,8.851,123.343562,Medium

##### Station Coverage Summary
This tells you which stations are “covering” the largest number of schools.

In [11]:
station_coverage = (
    analysis_df
    .groupby(["nearest_station_id", "nearest_station_name"], dropna=False)
    .agg(
        school_count=("School Name", "count"),
        avg_distance_km=("distance_km", "mean"),
        max_distance_km=("distance_km", "max"),
        avg_pm25=("PM2.5 (µg/m³)_mean", "mean"),
        avg_pm10=("PM10 (µg/m³)_mean", "mean")
    )
    .reset_index()
)

station_coverage["avg_distance_km"] = station_coverage["avg_distance_km"].round(2)
station_coverage["max_distance_km"] = station_coverage["max_distance_km"].round(2)
station_coverage["avg_pm25"] = station_coverage["avg_pm25"].round(2)
station_coverage["avg_pm10"] = station_coverage["avg_pm10"].round(2)

station_coverage = station_coverage.sort_values(
    by="school_count", ascending=False
).reset_index(drop=True)

station_coverage.head(20)

,nearest_station_id,nearest_station_name,school_count,avg_distance_km,max_distance_km,avg_pm25,avg_pm10
0,STN_025,Mundka,247,3.05,9.94,114.85,267.95
1,STN_026,NSIT Dwarka,239,3.55,10.93,73.00,165.37
2,STN_016,"IHBAS, Dilshad Garden",199,2.39,4.08,74.73,160.06
3,STN_041,Sonia Vihar,179,2.53,4.43,96.23,191.77
4,STN_033,Patparganj,145,2.44,5.07,101.34,219.14
5,STN_013,Dwarka-Sector 8,91,2.65,7.87,101.30,217.44
6,STN_034,Punjabi Bagh,88,2.43,4.82,107.77,201.52
7,STN_038,Rohini,81,2.31,4.00,116.04,232.26
8,STN_012,Dr. Karni Singh Shooting Range,74,3.77,6.44,92.05,179.47
9,STN_009,Chandni Chowk,71,1.85,4.10,97.67,203.53
10,STN_003,Ashok Vihar,63,1.82,3.33,112.19,223.25
11,STN_008,Cantonment Area,57,3.16,5.58,NaN,NaN
12,STN_032,Okhla Phase-2,55,2.71,7.14,95.75,214.39
13,STN_005,Bawana,55,5.45,11.34,123.34,207.45
14,STN_045,Wazirpur,51,1.62,3.23,124.29,281.58
15,STN_035,Pusa (DPCC),48,2.87,5.28,88.32,196.34
16,STN_021,Jahangirpuri,48,2.19,4.65,130.80,262.52
17,STN_044,Vivek Vihar,44,1.09,2.33,113.48,212.34
18,STN_002,Anand Vihar,43,2.13,4.82,122.06,261.41
19,STN_006,Burari Crossing,39,2.48,6.95,96.97,184.91

##### Confidence Summary
This gives you a quick view of how reliable your nearest-station mapping is.

In [12]:
confidence_summary = (
    analysis_df
    .groupby("exposure_confidence", dropna=False)
    .agg(
        school_count=("School Name", "count"),
        avg_distance_km=("distance_km", "mean"),
        max_distance_km=("distance_km", "max"),
        avg_pm25=("PM2.5 (µg/m³)_mean", "mean")
    )
    .reset_index()
)

confidence_summary["avg_distance_km"] = confidence_summary["avg_distance_km"].round(2)
confidence_summary["max_distance_km"] = confidence_summary["max_distance_km"].round(2)
confidence_summary["avg_pm25"] = confidence_summary["avg_pm25"].round(2)

confidence_summary

,exposure_confidence,school_count,avg_distance_km,max_distance_km,avg_pm25
0,High,2260,2.38,4.99,98.02
1,Low,9,11.28,15.20,90.20
2,Medium,154,6.22,9.94,98.92

##### Export All Summary Files

In [13]:
district_summary.to_csv(OUT_DIR / "district_exposure_summary.csv", index=False)
type_summary.to_csv(OUT_DIR / "type_exposure_summary.csv", index=False)
level_summary.to_csv(OUT_DIR / "level_exposure_summary.csv", index=False)
top_exposed_schools.to_csv(OUT_DIR / "top_exposed_schools.csv", index=False)
farthest_schools.to_csv(OUT_DIR / "farthest_schools.csv", index=False)
station_coverage.to_csv(OUT_DIR / "station_coverage_summary.csv", index=False)
confidence_summary.to_csv(OUT_DIR / "exposure_confidence_summary.csv", index=False)

print("Saved files:")
print(OUT_DIR / "district_exposure_summary.csv")
print(OUT_DIR / "type_exposure_summary.csv")
print(OUT_DIR / "level_exposure_summary.csv")
print(OUT_DIR / "top_exposed_schools.csv")
print(OUT_DIR / "farthest_schools.csv")
print(OUT_DIR / "station_coverage_summary.csv")
print(OUT_DIR / "exposure_confidence_summary.csv")

Saved files:
../data/processed/district_exposure_summary.csv
../data/processed/type_exposure_summary.csv
../data/processed/level_exposure_summary.csv
../data/processed/top_exposed_schools.csv
../data/processed/farthest_schools.csv
../data/processed/station_coverage_summary.csv
../data/processed/exposure_confidence_summary.csv

##### What Each Output Means
district_exposure_summary.csv = average exposure by district.

type_exposure_summary.csv = average exposure by school type.

level_exposure_summary.csv = average exposure by education level.

top_exposed_schools.csv = schools ranked by highest PM2.5 exposure.

farthest_schools.csv = schools farthest from any station, useful for monitoring-gap analysis.

station_coverage_summary.csv = which stations are assigned the most schools.

exposure_confidence_summary.csv = how many schools are High/Medium/Low confidence based on distance.

In [14]:
district_summary.head(10)

,District,school_count,avg_pm25,median_pm25,avg_pm10,avg_no2,avg_distance_km,max_distance_km,unique_stations_used
0,North West B-II,146,115.51,116.04,237.36,37.43,3.81,11.34,5
1,North West B-I,180,114.84,114.85,253.21,48.54,2.25,5.98,6
2,North West A,225,111.45,112.19,225.67,38.81,2.44,8.92,12
3,North,98,102.38,97.67,205.04,44.66,2.27,4.18,7
4,East,251,102.11,101.34,217.35,51.16,2.38,7.87,9
5,West A,117,96.86,94.28,198.55,47.70,2.65,5.58,8
6,South West A,90,95.51,88.32,192.92,48.14,2.15,5.07,10
7,South East,177,95.00,92.05,198.71,49.11,2.49,7.14,7
8,South,139,93.50,92.05,186.76,40.98,2.41,7.50,9
9,North East-I,186,93.47,96.23,187.61,35.50,2.59,6.95,3

In [15]:
type_summary

,Type,school_count,avg_pm25,median_pm25,avg_pm10,avg_no2,avg_distance_km,max_distance_km,unique_stations_used
0,Govt,1082,98.37,97.67,205.36,45.70,2.6,10.93,43
1,Unaided,1341,97.77,97.67,205.06,44.73,2.7,15.20,44

In [16]:
top_exposed_schools.head(10)

,District,School Name,Address,Type,SchoolLevel,nearest_station_name,distance_km,PM2.5 (µg/m³)_mean,PM10 (µg/m³)_mean,NO2 (µg/m³)_mean,exposure_confidence
0,South,ST. ANTHONYS SR. SEC SCHOOL,"C-6, S.D-A, Hauz Khas, Pin-110016",Unaided,Sr.Secondary,IIT Delhi,0.901,159.850323,261.914516,57.109355,High
1,South,MOTHERS INTERNATIONAL SCHOOL,SRI AUROBINDO NEW DELHI - 110016,Unaided,Sr.Secondary,IIT Delhi,0.929,159.850323,261.914516,57.109355,High
2,South,MIRAMBIKA FREE PROGRESS SCHOOL,"SRI AUROBINDO EDUCATION SOCIETY, SRI AUROBINDO...",Unaided,Secondary,IIT Delhi,1.025,159.850323,261.914516,57.109355,High
3,South,ST. PAULS SCHOOL,"C-3, SDA, HAUZ KHAS NEW DELHI",Unaided,Sr.Secondary,IIT Delhi,1.082,159.850323,261.914516,57.109355,High
4,South,SAHODYA SR. SECONDARY SCHOOL,"C-1, Safdarjang Development Area, New Delhi-11...",Unaided,Sr.Secondary,IIT Delhi,1.424,159.850323,261.914516,57.109355,High
5,North West A,PUBLIC MODEL SCHOOL,K - 244 - 246 JAHANGIR PURI DELHI - 110033,Unaided,Middle,Jahangirpuri,0.385,130.802849,262.515753,50.482822,High
6,North West A,"Jahangirpuri, Block K-GGSSS","K-Block, Jahangripuri",Govt,Sr.Secondary,Jahangirpuri,0.438,130.802849,262.515753,50.482822,High
7,North West A,"Jahangirpuri, Block K-GBSSS","Block-K, Jahangirpuri",Govt,Sr.Secondary,Jahangirpuri,0.442,130.802849,262.515753,50.482822,High
8,North West A,"Jahangirpuri, Block D-GBSSS","Jahangirpuri, Delhi-33",Govt,Sr.Secondary,Jahangirpuri,0.533,130.802849,262.515753,50.482822,High
9,North West A,"Sarvodaya Kanya Vidyalaya (Rani Chennama), D -...","D-Block, Jahangirpuri",Govt,Sarvodaya Sr.Secondary,Jahangirpuri,0.592,130.802849,262.515753,50.482822,High

In [17]:
farthest_schools.head(10)

,District,School Name,Address,Type,SchoolLevel,nearest_station_name,distance_km,PM2.5 (µg/m³)_mean,exposure_confidence
0,West B,SUNRISE CONVENT SCHOOL,"H.NoD-59/280,StreetNo D-Block,Sector-15,Villag...",Unaided,Middle,Aya Nagar,15.200,76.782384,Low
1,North West B-II,R.K. International School,"V & PO Nizampur, Delhi",Unaided,Secondary,Bawana,11.335,123.343562,Low
2,West B,"Govt. Boys Sr. Sec. School, Tikri Kalan, No. 1...",Tikri Kalan,Govt,Sr.Secondary,NSIT Dwarka,10.928,72.996822,Low
3,West B,"Government Girls Sr. Sec. School, Tikri Kalan",Tikri Kalan,Govt,Sr.Secondary,NSIT Dwarka,10.928,72.996822,Low
4,West B,"Sarvodaya Kanya Vidyalaya, Tikri Kalan-1617012",Tikri Kalan,Govt,Sarvodaya Sr.Secondary,NSIT Dwarka,10.925,72.996822,Low
5,West B,"Government Boys Sr. Sec. School, Tikri Kalan, ...",Tikri Kalan,Govt,Sr.Secondary,NSIT Dwarka,10.925,72.996822,Low
6,North West B-II,Nizam Pur-Sarvodaya (Co-ed) Vidyalaya,Vill & P. O. Nizampur,Govt,Sarvodaya Sr.Secondary,Bawana,10.590,123.343562,Low
7,North West B-II,Vanasthali Public School,"Ghewra, Nizampur Main Road, Delhi 81",Unaided,Sr.Secondary,Bawana,10.514,123.343562,Low
8,West B,NEW BAL VIKAS PUBLIC SCHOOL,TIKRI KALAN,Unaided,Middle,NSIT Dwarka,10.144,72.996822,Low
9,North West B-II,Sawada(Ghevra) Colony H-Block- SV,Sawada(Ghevra) Colony H-Block,Govt,Sarvodaya Sr.Secondary,Mundka,9.940,114.845699,Medium

##### Delhi’s outer and northwestern school belts are both more polluted and farther from monitoring stations, while some southern schools are among the highest-exposure schools despite being close to strong monitoring stations like IIT Delhi.